_BASE_: "../Base-multiswints_swin.yaml"
MODEL:
  WEIGHTS: "./output/generic/mixtrain/model_0139999.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
  LANGUAGE_HEAD:
    NUM_CLASSES: 8
    PREDICTOR: V1LanguagePredictor
    INPUT_H: 32
    INPUT_W: 32
    INPUT_C: 256
    CONV1_C: 64
    CONV2_C: 32
DATASETS:
  TRAIN: ("MLT19_train", "MLT17_val", "MLT17_train",)
  TEST:  ("MLT19_test",)
  TASK: (1,4,)
SEQUENCE:
  MULTI: True
  BOS_TOKEN: 0
  BEAM_SEARCH: False
  ANY:
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 8000
  LANGUAGES:
  - any
  LANGUAGES_ENABLED:
  - any
  LANGUAGES_UNFREEZED:
  - any
  NUM_SEQ_HEADS: 1
  RESIZE_HEIGHT: 16
  RESIZE_WIDTH: 64
  LOSS_WEIGHT: 0.5
SOLVER:
  BASE_LR: 0.00001
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  IMS_PER_BATCH: 20
  STEPS: (60000,)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 5000
  DISPLAY_FREQ: 50
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TEST: 2000
  MAX_SIZE_TEST: 2824
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864, 896,)
  MAX_SIZE_TRAIN: 1600
TEST:
  RUN_ALL_HEADS: True
  EVAL_PERIOD: 10000
  DET_CONF_THRESH: 0.4
  LANG_CONF_THRESH: 0.1
  SEQ_CONF_THRESH: 0.4
  SAMPLE: -1  # set -1 to use full sets
OUTPUT_DIR: "./output/generic/finetune/"