_BASE_: "../Base-multiswints_swin.yaml"
MODEL:
  # WEIGHTS: "output/model/220907/multiswints_finetune/model_0054999.pth"
  # for coeus
  WEIGHTS: "/dataset/s3/cv_platform/JeremyFeng/ckpt/SWINTS/multiswints/220909/multiswints_mixtrain_MLT19_MLT17/model_0087999.pth"
  BACKBONE:
    FREEZE_AT: 5   # freeze swin backbone layers range(0, FREEZE_AT-1)
    FREEZE_BN: True
  FPN:
    FREEZE: True
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
    FREEZE: True
    HEAD:
      FREEZE: True
  LANGUAGE_HEAD:
    NUM_CLASSES: 8
    PREDICTOR: V1LanguagePredictor
    INPUT_H: 32
    INPUT_W: 32
    INPUT_C: 256
    CONV1_C: 64
    CONV2_C: 32
    FREEZE: True
  REC_HEAD:
    PRETRAIN: False
    E2ETrain: True
    GuideByGT: True
    FREEZE: True
DATASETS:
  TRAIN: ("MLT19_train", "MLT17_train", "MLT17_val", "totaltext_train", "totaltext_test", "ArT19_train", "RCTW17_train", "LSVT19_train", "icdar_2015_train", "icdar_2015_test", "icdar_2013_train")
  TEST:  ("MLT19_val",)
  TASK: (1,3,4,)
SEQUENCE:
  MULTI: True
  BOS_TOKEN: 0
  BEAM_SEARCH: False
  ARABIC:
    EMBED_SIZE: 100
    HIDDEN_SIZE: 256
    NUM_CHAR: 80
  BENGALI:
    EMBED_SIZE: 100
    HIDDEN_SIZE: 256
    NUM_CHAR: 110
  CHINESE:
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 5200
  DEVANAGARI:
    EMBED_SIZE: 100
    HIDDEN_SIZE: 256
    NUM_CHAR: 110
  HANGUL:
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 1500
  JAPANESE:
    EMBED_SIZE: 200
    HIDDEN_SIZE: 256
    NUM_CHAR: 2242
  LATIN:
    EMBED_SIZE: 150
    HIDDEN_SIZE: 256
    NUM_CHAR: 250
  SYMBOL:
    EMBED_SIZE: 100
    HIDDEN_SIZE: 256
    NUM_CHAR: 60
  LANGUAGES:
  - ar
  - bn
  - hi
  - ja
  - ko
  - la
  - zh
  - symbol
  LANGUAGES_ENABLED:
  - ar
  - bn
  - hi
  - ja
  - ko
  - la
  - zh
  - symbol
  LANGUAGES_UNFREEZED:
  - ar
  - bn
  - hi
  - ja
  - ko
  - la
  - zh
  - symbol
  NUM_SEQ_HEADS: 8
  RESIZE_HEIGHT: 16
  RESIZE_WIDTH: 64
  LOSS_WEIGHT: 0.5
SOLVER:
  BASE_LR: 0.0001
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  IMS_PER_BATCH: 36
  STEPS: (40000, 80000,)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 3000
  DISPLAY_FREQ: 20
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TEST: 2000
  MAX_SIZE_TEST: 2824
  MIN_SIZE_TRAIN: (800, 864, 896, 1024, 1280, 1366, 1600, 1920)
  MAX_SIZE_TRAIN: 2824
TEST:
  RUN_ALL_HEADS: True
  EVAL_PERIOD: 3000
  DET_CONF_THRESH: 0.4
  LANG_CONF_THRESH: 0.1
  SEQ_CONF_THRESH: 0.4
  SAMPLE: -1  # set -1 to use full sets
OUTPUT_DIR: "./output/220916/multiswints_ocronly_rest_encoder_decoder"
# model save in s3://cv_platform/JeremyFeng/ckpt/SWINTS/multiswints/220916/multiswints_ocronly_rest_encoder_decoder/