from detectron2.config import CfgNode as CN


def add_SWINTS_config(cfg):
    """
    Add config for SWINTS.
    """
    cfg.MODEL.SWINTS = CN()
    cfg.MODEL.SWINTS.FREEZE = False
    cfg.MODEL.SWINTS.NUM_CLASSES = 80
    cfg.MODEL.SWINTS.NUM_PROPOSALS = 300
    cfg.MODEL.SWINTS.TEST_NUM_PROPOSALS = 100

    # RCNN Head.
    cfg.MODEL.SWINTS.HEAD = CN()
    cfg.MODEL.SWINTS.HEAD.FREEZE = False
    cfg.MODEL.SWINTS.NHEADS = 8
    cfg.MODEL.SWINTS.DROPOUT = 0.0
    cfg.MODEL.SWINTS.DIM_FEEDFORWARD = 2048
    cfg.MODEL.SWINTS.ACTIVATION = 'relu'
    cfg.MODEL.SWINTS.HIDDEN_DIM = 256
    cfg.MODEL.SWINTS.NUM_CLS = 3
    cfg.MODEL.SWINTS.NUM_REG = 3
    cfg.MODEL.SWINTS.NUM_MASK = 3
    cfg.MODEL.SWINTS.NUM_HEADS = 6

    cfg.MODEL.SWINTS.MASK_DIM = 60


    # Dynamic Conv.
    cfg.MODEL.SWINTS.NUM_DYNAMIC = 2
    cfg.MODEL.SWINTS.DIM_DYNAMIC = 64

    # Recognition Head
    cfg.MODEL.REC_HEAD = CN()
    cfg.MODEL.REC_HEAD.FREEZE = False
    cfg.MODEL.REC_HEAD.PRETRAIN = True
    cfg.MODEL.REC_HEAD.E2ETrain = False
    cfg.MODEL.REC_HEAD.GuideByGT = False
    cfg.MODEL.REC_HEAD.BATCH_SIZE = 48
    cfg.MODEL.REC_HEAD.POOLER_RESOLUTION = (28,28)
    cfg.MODEL.REC_HEAD.RESOLUTION = (32, 32)
    cfg.MODEL.REC_HEAD.NUM_CLASSES = 107
    cfg.MODEL.REC_HEAD.MAX_LENGTH = 100
    
    # Script Identify Head
    cfg.MODEL.LANGUAGE_HEAD = CN()
    cfg.MODEL.LANGUAGE_HEAD.FREEZE = False
    cfg.MODEL.LANGUAGE_HEAD.NUM_CLASSES = 2
    cfg.MODEL.LANGUAGE_HEAD.PREDICTOR = "V1LanguagePredictor"
    cfg.MODEL.LANGUAGE_HEAD.LOSS_WEIGHT = 1.0
    cfg.MODEL.LANGUAGE_HEAD.INPUT_C = 256
    cfg.MODEL.LANGUAGE_HEAD.INPUT_H = 40
    cfg.MODEL.LANGUAGE_HEAD.INPUT_W = 40
    cfg.MODEL.LANGUAGE_HEAD.CONV1_C = 64
    cfg.MODEL.LANGUAGE_HEAD.CONV2_C = 32
    
    # Character-map related configs
    cfg.CHAR_MAP = CN()
    # char map directory
    cfg.CHAR_MAP.DIR = ""
    
    # Supported Recognition Language
    cfg.SEQUENCE = CN()
    cfg.SEQUENCE.MULTI = False
    cfg.SEQUENCE.NUM_SEQ_HEADS = 1
    # Enabled languages for language identification purpose
    cfg.SEQUENCE.LANGUAGES = ("ar", "bn", "hi", "ja", "ko", "la", "zh", "symbol")
    cfg.SEQUENCE.LANGUAGES_ENABLED = ("ar", "bn", "hi", "ja", "ko", "la", "zh", "symbol")
    
    cfg.SEQUENCE.LANGUAGES_UNFREEZED = None  # requires yacs >= 0.1.8
    cfg.SEQUENCE.NUM_CHAR = 36
    cfg.SEQUENCE.EMBED_SIZE = 38
    cfg.SEQUENCE.HIDDEN_SIZE = 256
    # Whether beam search is enabled at test time
    cfg.SEQUENCE.BEAM_SEARCH = True
    cfg.SEQUENCE.BOS_TOKEN = 0
    cfg.SEQUENCE.MAX_LENGTH = 32
    cfg.SEQUENCE.TEACHER_FORCE_RATIO = 1.0
    cfg.SEQUENCE.TWO_CONV = False
    cfg.SEQUENCE.MEAN_SCORE = False
    cfg.SEQUENCE.RESIZE_HEIGHT = 16
    cfg.SEQUENCE.RESIZE_WIDTH = 64
    cfg.SEQUENCE.DECODER_LOSS = "NLLLoss"
    cfg.SEQUENCE.LOSS_WEIGHT = 0.5
    
    cfg.SEQUENCE.LOSS_WEIGHT_BASE = 0.0

    cfg.SEQUENCE.EN_NUM = CN()
    cfg.SEQUENCE.EN_NUM.ARCH = "seq2seq_a"
    cfg.SEQUENCE.EN_NUM.NUM_CHAR = 36
    cfg.SEQUENCE.EN_NUM.EMBED_SIZE = 38
    cfg.SEQUENCE.EN_NUM.HIDDEN_SIZE = 256

    cfg.SEQUENCE.EN_NUM_36 = CN()
    cfg.SEQUENCE.EN_NUM_36.ARCH = "seq2seq_a"
    cfg.SEQUENCE.EN_NUM_36.NUM_CHAR = 36
    cfg.SEQUENCE.EN_NUM_36.EMBED_SIZE = 38
    cfg.SEQUENCE.EN_NUM_36.HIDDEN_SIZE = 256

    cfg.SEQUENCE.AMHARIC = CN()
    cfg.SEQUENCE.AMHARIC.ARCH = "seq2seq_a"
    cfg.SEQUENCE.AMHARIC.NUM_CHAR = 370
    cfg.SEQUENCE.AMHARIC.EMBED_SIZE = 50
    cfg.SEQUENCE.AMHARIC.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ANY = CN()
    cfg.SEQUENCE.ANY.ARCH = "seq2seq_a"
    cfg.SEQUENCE.ANY.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY.EMBED_SIZE = 250
    cfg.SEQUENCE.ANY.HIDDEN_SIZE = 320

    cfg.SEQUENCE.ANY1 = CN()
    cfg.SEQUENCE.ANY1.ARCH = "ctc_lstm"
    cfg.SEQUENCE.ANY1.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY1.EMBED_SIZE = 200
    cfg.SEQUENCE.ANY1.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ANY2 = CN()
    cfg.SEQUENCE.ANY2.ARCH = "ctc_lstm"
    cfg.SEQUENCE.ANY2.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY2.EMBED_SIZE = 200
    cfg.SEQUENCE.ANY2.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ANY3 = CN()
    cfg.SEQUENCE.ANY3.ARCH = "ctc_lstm"
    cfg.SEQUENCE.ANY3.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY3.EMBED_SIZE = 200
    cfg.SEQUENCE.ANY3.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ANY4 = CN()
    cfg.SEQUENCE.ANY4.ARCH = "ctc_lstm"
    cfg.SEQUENCE.ANY4.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY4.EMBED_SIZE = 200
    cfg.SEQUENCE.ANY4.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ANY5 = CN()
    cfg.SEQUENCE.ANY5.ARCH = "ctc_lstm"
    cfg.SEQUENCE.ANY5.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY5.EMBED_SIZE = 200
    cfg.SEQUENCE.ANY5.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ANY6 = CN()
    cfg.SEQUENCE.ANY6.ARCH = "ctc_lstm"
    cfg.SEQUENCE.ANY6.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY6.EMBED_SIZE = 200
    cfg.SEQUENCE.ANY6.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ANY7 = CN()
    cfg.SEQUENCE.ANY7.ARCH = "ctc_lstm"
    cfg.SEQUENCE.ANY7.NUM_CHAR = 11000
    cfg.SEQUENCE.ANY7.EMBED_SIZE = 200
    cfg.SEQUENCE.ANY7.HIDDEN_SIZE = 256

    cfg.SEQUENCE.ARABIC = CN()
    cfg.SEQUENCE.ARABIC.ARCH = "seq2seq_a"
    cfg.SEQUENCE.ARABIC.NUM_CHAR = 150
    cfg.SEQUENCE.ARABIC.EMBED_SIZE = 30
    cfg.SEQUENCE.ARABIC.HIDDEN_SIZE = 256

    cfg.SEQUENCE.BENGALI = CN()
    cfg.SEQUENCE.BENGALI.ARCH = "seq2seq_a"
    cfg.SEQUENCE.BENGALI.NUM_CHAR = 120
    cfg.SEQUENCE.BENGALI.EMBED_SIZE = 30
    cfg.SEQUENCE.BENGALI.HIDDEN_SIZE = 256

    cfg.SEQUENCE.BULGARIAN = CN()
    cfg.SEQUENCE.BULGARIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.BULGARIAN.NUM_CHAR = 110
    cfg.SEQUENCE.BULGARIAN.EMBED_SIZE = 30
    cfg.SEQUENCE.BULGARIAN.HIDDEN_SIZE = 192

    cfg.SEQUENCE.BURMESE = CN()
    cfg.SEQUENCE.BURMESE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.BURMESE.NUM_CHAR = 160
    cfg.SEQUENCE.BURMESE.EMBED_SIZE = 30
    cfg.SEQUENCE.BURMESE.HIDDEN_SIZE = 192

    cfg.SEQUENCE.CHINESE = CN()
    cfg.SEQUENCE.CHINESE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.CHINESE.NUM_CHAR = 6100
    cfg.SEQUENCE.CHINESE.EMBED_SIZE = 50
    cfg.SEQUENCE.CHINESE.HIDDEN_SIZE = 256

    cfg.SEQUENCE.CROATIAN = CN()
    cfg.SEQUENCE.CROATIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.CROATIAN.NUM_CHAR = 110
    cfg.SEQUENCE.CROATIAN.EMBED_SIZE = 100
    cfg.SEQUENCE.CROATIAN.HIDDEN_SIZE = 192

    cfg.SEQUENCE.CYRILLIC = CN()
    cfg.SEQUENCE.CYRILLIC.ARCH = "seq2seq_a"
    cfg.SEQUENCE.CYRILLIC.NUM_CHAR = 130
    cfg.SEQUENCE.CYRILLIC.EMBED_SIZE = 30
    cfg.SEQUENCE.CYRILLIC.HIDDEN_SIZE = 256

    cfg.SEQUENCE.DEVANAGARI = CN()
    cfg.SEQUENCE.DEVANAGARI.ARCH = "seq2seq_a"
    cfg.SEQUENCE.DEVANAGARI.NUM_CHAR = 130
    cfg.SEQUENCE.DEVANAGARI.EMBED_SIZE = 30
    cfg.SEQUENCE.DEVANAGARI.HIDDEN_SIZE = 256

    cfg.SEQUENCE.DUTCH = CN()
    cfg.SEQUENCE.DUTCH.ARCH = "seq2seq_a"
    cfg.SEQUENCE.DUTCH.NUM_CHAR = 100
    cfg.SEQUENCE.DUTCH.EMBED_SIZE = 30
    cfg.SEQUENCE.DUTCH.HIDDEN_SIZE = 192

    cfg.SEQUENCE.ENGLISH = CN()
    cfg.SEQUENCE.ENGLISH.ARCH = "seq2seq_a"
    cfg.SEQUENCE.ENGLISH.NUM_CHAR = 120
    cfg.SEQUENCE.ENGLISH.EMBED_SIZE = 30
    cfg.SEQUENCE.ENGLISH.HIDDEN_SIZE = 256

    cfg.SEQUENCE.FRENCH = CN()
    cfg.SEQUENCE.FRENCH.ARCH = "seq2seq_a"
    cfg.SEQUENCE.FRENCH.NUM_CHAR = 160
    cfg.SEQUENCE.FRENCH.EMBED_SIZE = 30
    cfg.SEQUENCE.FRENCH.HIDDEN_SIZE = 192

    cfg.SEQUENCE.GERMAN = CN()
    cfg.SEQUENCE.GERMAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.GERMAN.NUM_CHAR = 120
    cfg.SEQUENCE.GERMAN.EMBED_SIZE = 30
    cfg.SEQUENCE.GERMAN.HIDDEN_SIZE = 192

    cfg.SEQUENCE.GREEK = CN()
    cfg.SEQUENCE.GREEK.ARCH = "seq2seq_a"
    cfg.SEQUENCE.GREEK.NUM_CHAR = 120
    cfg.SEQUENCE.GREEK.EMBED_SIZE = 30
    cfg.SEQUENCE.GREEK.HIDDEN_SIZE = 192

    cfg.SEQUENCE.GUJARATI = CN()
    cfg.SEQUENCE.GUJARATI.ARCH = "seq2seq_a"
    cfg.SEQUENCE.GUJARATI.NUM_CHAR = 120
    cfg.SEQUENCE.GUJARATI.EMBED_SIZE = 30
    cfg.SEQUENCE.GUJARATI.HIDDEN_SIZE = 192

    cfg.SEQUENCE.HANGUL = CN()
    cfg.SEQUENCE.HANGUL.ARCH = "seq2seq_a"
    cfg.SEQUENCE.HANGUL.NUM_CHAR = 2000
    cfg.SEQUENCE.HANGUL.EMBED_SIZE = 50
    cfg.SEQUENCE.HANGUL.HIDDEN_SIZE = 256

    cfg.SEQUENCE.HEBREW = CN()
    cfg.SEQUENCE.HEBREW.ARCH = "seq2seq_a"
    cfg.SEQUENCE.HEBREW.NUM_CHAR = 110
    cfg.SEQUENCE.HEBREW.EMBED_SIZE = 30
    cfg.SEQUENCE.HEBREW.HIDDEN_SIZE = 192

    cfg.SEQUENCE.HUNGARIAN = CN()
    cfg.SEQUENCE.HUNGARIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.HUNGARIAN.NUM_CHAR = 120
    cfg.SEQUENCE.HUNGARIAN.EMBED_SIZE = 30
    cfg.SEQUENCE.HUNGARIAN.HIDDEN_SIZE = 192

    cfg.SEQUENCE.INDONESIAN = CN()
    cfg.SEQUENCE.INDONESIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.INDONESIAN.NUM_CHAR = 100
    cfg.SEQUENCE.INDONESIAN.EMBED_SIZE = 30
    cfg.SEQUENCE.INDONESIAN.HIDDEN_SIZE = 192

    cfg.SEQUENCE.ITALIAN = CN()
    cfg.SEQUENCE.ITALIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.ITALIAN.NUM_CHAR = 110
    cfg.SEQUENCE.ITALIAN.EMBED_SIZE = 30
    cfg.SEQUENCE.ITALIAN.HIDDEN_SIZE = 192

    cfg.SEQUENCE.JAPANESE = CN()
    cfg.SEQUENCE.JAPANESE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.JAPANESE.NUM_CHAR = 3300
    cfg.SEQUENCE.JAPANESE.EMBED_SIZE = 50
    cfg.SEQUENCE.JAPANESE.HIDDEN_SIZE = 256

    cfg.SEQUENCE.JAVANESE = CN()
    cfg.SEQUENCE.JAVANESE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.JAVANESE.NUM_CHAR = 110
    cfg.SEQUENCE.JAVANESE.EMBED_SIZE = 30
    cfg.SEQUENCE.JAVANESE.HIDDEN_SIZE = 168

    cfg.SEQUENCE.KANA = CN()
    cfg.SEQUENCE.KANA.ARCH = "seq2seq_a"
    cfg.SEQUENCE.KANA.NUM_CHAR = 210
    cfg.SEQUENCE.KANA.EMBED_SIZE = 30
    cfg.SEQUENCE.KANA.HIDDEN_SIZE = 256

    cfg.SEQUENCE.KANNADA = CN()
    cfg.SEQUENCE.KANNADA.ARCH = "seq2seq_a"
    cfg.SEQUENCE.KANNADA.NUM_CHAR = 120
    cfg.SEQUENCE.KANNADA.EMBED_SIZE = 30
    cfg.SEQUENCE.KANNADA.HIDDEN_SIZE = 192

    cfg.SEQUENCE.KHMER = CN()
    cfg.SEQUENCE.KHMER.ARCH = "seq2seq_a"
    cfg.SEQUENCE.KHMER.NUM_CHAR = 140
    cfg.SEQUENCE.KHMER.EMBED_SIZE = 30
    cfg.SEQUENCE.KHMER.HIDDEN_SIZE = 192

    cfg.SEQUENCE.LATIN = CN()
    cfg.SEQUENCE.LATIN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.LATIN.NUM_CHAR = 230
    cfg.SEQUENCE.LATIN.EMBED_SIZE = 50
    cfg.SEQUENCE.LATIN.HIDDEN_SIZE = 256

    cfg.SEQUENCE.MALAY = CN()
    cfg.SEQUENCE.MALAY.ARCH = "seq2seq_a"
    cfg.SEQUENCE.MALAY.NUM_CHAR = 110
    cfg.SEQUENCE.MALAY.EMBED_SIZE = 30
    cfg.SEQUENCE.MALAY.HIDDEN_SIZE = 192

    cfg.SEQUENCE.MALAYALAM = CN()
    cfg.SEQUENCE.MALAYALAM.ARCH = "seq2seq_a"
    cfg.SEQUENCE.MALAYALAM.NUM_CHAR = 130
    cfg.SEQUENCE.MALAYALAM.EMBED_SIZE = 30
    cfg.SEQUENCE.MALAYALAM.HIDDEN_SIZE = 192

    cfg.SEQUENCE.MARATHI = CN()
    cfg.SEQUENCE.MARATHI.ARCH = "seq2seq_a"
    cfg.SEQUENCE.MARATHI.NUM_CHAR = 130
    cfg.SEQUENCE.MARATHI.EMBED_SIZE = 30
    cfg.SEQUENCE.MARATHI.HIDDEN_SIZE = 192

    cfg.SEQUENCE.NUMBER = CN()
    cfg.SEQUENCE.NUMBER.ARCH = "seq2seq_a"
    cfg.SEQUENCE.NUMBER.NUM_CHAR = 20
    cfg.SEQUENCE.NUMBER.EMBED_SIZE = 10
    cfg.SEQUENCE.NUMBER.HIDDEN_SIZE = 64

    cfg.SEQUENCE.PERSIAN = CN()
    cfg.SEQUENCE.PERSIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.PERSIAN.NUM_CHAR = 160
    cfg.SEQUENCE.PERSIAN.EMBED_SIZE = 50
    cfg.SEQUENCE.PERSIAN.HIDDEN_SIZE = 256

    cfg.SEQUENCE.POLISH = CN()
    cfg.SEQUENCE.POLISH.ARCH = "seq2seq_a"
    cfg.SEQUENCE.POLISH.NUM_CHAR = 120
    cfg.SEQUENCE.POLISH.EMBED_SIZE = 30
    cfg.SEQUENCE.POLISH.HIDDEN_SIZE = 192

    cfg.SEQUENCE.PORTUGUESE = CN()
    cfg.SEQUENCE.PORTUGUESE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.PORTUGUESE.NUM_CHAR = 110
    cfg.SEQUENCE.PORTUGUESE.EMBED_SIZE = 30
    cfg.SEQUENCE.PORTUGUESE.HIDDEN_SIZE = 192

    cfg.SEQUENCE.PUNJABI = CN()
    cfg.SEQUENCE.PUNJABI.ARCH = "seq2seq_a"
    cfg.SEQUENCE.PUNJABI.NUM_CHAR = 120
    cfg.SEQUENCE.PUNJABI.EMBED_SIZE = 30
    cfg.SEQUENCE.PUNJABI.HIDDEN_SIZE = 192

    cfg.SEQUENCE.ROMANIAN = CN()
    cfg.SEQUENCE.ROMANIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.ROMANIAN.NUM_CHAR = 110
    cfg.SEQUENCE.ROMANIAN.EMBED_SIZE = 30
    cfg.SEQUENCE.ROMANIAN.HIDDEN_SIZE = 192

    cfg.SEQUENCE.RUSSIAN = CN()
    cfg.SEQUENCE.RUSSIAN.ARCH = "seq2seq_a"
    cfg.SEQUENCE.RUSSIAN.NUM_CHAR = 140
    cfg.SEQUENCE.RUSSIAN.EMBED_SIZE = 30
    cfg.SEQUENCE.RUSSIAN.HIDDEN_SIZE = 256

    cfg.SEQUENCE.SINHALA = CN()
    cfg.SEQUENCE.SINHALA.ARCH = "seq2seq_a"
    cfg.SEQUENCE.SINHALA.NUM_CHAR = 120
    cfg.SEQUENCE.SINHALA.EMBED_SIZE = 30
    cfg.SEQUENCE.SINHALA.HIDDEN_SIZE = 256

    cfg.SEQUENCE.SPANISH = CN()
    cfg.SEQUENCE.SPANISH.ARCH = "seq2seq_a"
    cfg.SEQUENCE.SPANISH.NUM_CHAR = 120
    cfg.SEQUENCE.SPANISH.EMBED_SIZE = 30
    cfg.SEQUENCE.SPANISH.HIDDEN_SIZE = 192

    cfg.SEQUENCE.SYMBOL = CN()
    cfg.SEQUENCE.SYMBOL.ARCH = "seq2seq_a"
    cfg.SEQUENCE.SYMBOL.NUM_CHAR = 60
    cfg.SEQUENCE.SYMBOL.EMBED_SIZE = 30
    cfg.SEQUENCE.SYMBOL.HIDDEN_SIZE = 64

    cfg.SEQUENCE.TAGALOG = CN()
    cfg.SEQUENCE.TAGALOG.ARCH = "seq2seq_a"
    cfg.SEQUENCE.TAGALOG.NUM_CHAR = 110
    cfg.SEQUENCE.TAGALOG.EMBED_SIZE = 30
    cfg.SEQUENCE.TAGALOG.HIDDEN_SIZE = 192

    cfg.SEQUENCE.TAMIL = CN()
    cfg.SEQUENCE.TAMIL.ARCH = "seq2seq_a"
    cfg.SEQUENCE.TAMIL.NUM_CHAR = 110
    cfg.SEQUENCE.TAMIL.EMBED_SIZE = 30
    cfg.SEQUENCE.TAMIL.HIDDEN_SIZE = 256

    cfg.SEQUENCE.TELUGU = CN()
    cfg.SEQUENCE.TELUGU.ARCH = "seq2seq_a"
    cfg.SEQUENCE.TELUGU.NUM_CHAR = 130
    cfg.SEQUENCE.TELUGU.EMBED_SIZE = 30
    cfg.SEQUENCE.TELUGU.HIDDEN_SIZE = 192

    cfg.SEQUENCE.THAI = CN()
    cfg.SEQUENCE.THAI.ARCH = "seq2seq_a"
    cfg.SEQUENCE.THAI.NUM_CHAR = 210
    cfg.SEQUENCE.THAI.EMBED_SIZE = 30
    cfg.SEQUENCE.THAI.HIDDEN_SIZE = 192

    cfg.SEQUENCE.TURKISH = CN()
    cfg.SEQUENCE.TURKISH.ARCH = "seq2seq_a"
    cfg.SEQUENCE.TURKISH.NUM_CHAR = 120
    cfg.SEQUENCE.TURKISH.EMBED_SIZE = 30
    cfg.SEQUENCE.TURKISH.HIDDEN_SIZE = 192

    cfg.SEQUENCE.UNIFIEDAPU = CN()
    cfg.SEQUENCE.UNIFIEDAPU.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDAPU.NUM_CHAR = 250
    cfg.SEQUENCE.UNIFIEDAPU.EMBED_SIZE = 200
    cfg.SEQUENCE.UNIFIEDAPU.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDAPUE = CN()
    cfg.SEQUENCE.UNIFIEDAPUE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDAPUE.NUM_CHAR = 300
    cfg.SEQUENCE.UNIFIEDAPUE.EMBED_SIZE = 250
    cfg.SEQUENCE.UNIFIEDAPUE.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDBGHMP = CN()
    cfg.SEQUENCE.UNIFIEDBGHMP.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDBGHMP.NUM_CHAR = 400
    cfg.SEQUENCE.UNIFIEDBGHMP.EMBED_SIZE = 270
    cfg.SEQUENCE.UNIFIEDBGHMP.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDBKT = CN()
    cfg.SEQUENCE.UNIFIEDBKT.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDBKT.NUM_CHAR = 400
    cfg.SEQUENCE.UNIFIEDBKT.EMBED_SIZE = 250
    cfg.SEQUENCE.UNIFIEDBKT.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDCG = CN()
    cfg.SEQUENCE.UNIFIEDCG.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDCG.NUM_CHAR = 260
    cfg.SEQUENCE.UNIFIEDCG.EMBED_SIZE = 220
    cfg.SEQUENCE.UNIFIEDCG.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDCGE = CN()
    cfg.SEQUENCE.UNIFIEDCGE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDCGE.NUM_CHAR = 280
    cfg.SEQUENCE.UNIFIEDCGE.EMBED_SIZE = 220
    cfg.SEQUENCE.UNIFIEDCGE.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDCJ = CN()
    cfg.SEQUENCE.UNIFIEDCJ.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDCJ.NUM_CHAR = 9000
    cfg.SEQUENCE.UNIFIEDCJ.EMBED_SIZE = 2000
    cfg.SEQUENCE.UNIFIEDCJ.HIDDEN_SIZE = 320

    cfg.SEQUENCE.UNIFIEDCJE = CN()
    cfg.SEQUENCE.UNIFIEDCJE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDCJE.NUM_CHAR = 9000
    cfg.SEQUENCE.UNIFIEDCJE.EMBED_SIZE = 2000
    cfg.SEQUENCE.UNIFIEDCJE.HIDDEN_SIZE = 320

    cfg.SEQUENCE.UNIFIEDCYRILLIC = CN()
    cfg.SEQUENCE.UNIFIEDCYRILLIC.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDCYRILLIC.NUM_CHAR = 180
    cfg.SEQUENCE.UNIFIEDCYRILLIC.EMBED_SIZE = 180
    cfg.SEQUENCE.UNIFIEDCYRILLIC.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDDEVANAGARI = CN()
    cfg.SEQUENCE.UNIFIEDDEVANAGARI.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDDEVANAGARI.NUM_CHAR = 180
    cfg.SEQUENCE.UNIFIEDDEVANAGARI.EMBED_SIZE = 180
    cfg.SEQUENCE.UNIFIEDDEVANAGARI.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDKE = CN()
    cfg.SEQUENCE.UNIFIEDKE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDKE.NUM_CHAR = 2500
    cfg.SEQUENCE.UNIFIEDKE.EMBED_SIZE = 1500
    cfg.SEQUENCE.UNIFIEDKE.HIDDEN_SIZE = 320

    cfg.SEQUENCE.UNIFIEDKT = CN()
    cfg.SEQUENCE.UNIFIEDKT.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDKT.NUM_CHAR = 220
    cfg.SEQUENCE.UNIFIEDKT.EMBED_SIZE = 200
    cfg.SEQUENCE.UNIFIEDKT.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDLATIN1 = CN()
    cfg.SEQUENCE.UNIFIEDLATIN1.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDLATIN1.NUM_CHAR = 500
    cfg.SEQUENCE.UNIFIEDLATIN1.EMBED_SIZE = 270
    cfg.SEQUENCE.UNIFIEDLATIN1.HIDDEN_SIZE = 256

    cfg.SEQUENCE.UNIFIEDMST = CN()
    cfg.SEQUENCE.UNIFIEDMST.ARCH = "seq2seq_a"
    cfg.SEQUENCE.UNIFIEDMST.NUM_CHAR = 300
    cfg.SEQUENCE.UNIFIEDMST.EMBED_SIZE = 250
    cfg.SEQUENCE.UNIFIEDMST.HIDDEN_SIZE = 256

    cfg.SEQUENCE.URDU = CN()
    cfg.SEQUENCE.URDU.ARCH = "seq2seq_a"
    cfg.SEQUENCE.URDU.NUM_CHAR = 160
    cfg.SEQUENCE.URDU.EMBED_SIZE = 30
    cfg.SEQUENCE.URDU.HIDDEN_SIZE = 192

    cfg.SEQUENCE.VIETNAMESE = CN()
    cfg.SEQUENCE.VIETNAMESE.ARCH = "seq2seq_a"
    cfg.SEQUENCE.VIETNAMESE.NUM_CHAR = 260
    cfg.SEQUENCE.VIETNAMESE.EMBED_SIZE = 30
    cfg.SEQUENCE.VIETNAMESE.HIDDEN_SIZE = 256

    # Loss.
    cfg.MODEL.SWINTS.CLASS_WEIGHT = 2.0
    cfg.MODEL.SWINTS.GIOU_WEIGHT = 2.0
    cfg.MODEL.SWINTS.L1_WEIGHT = 5.0
    cfg.MODEL.SWINTS.REC_WEIGHT = 1.0
    cfg.MODEL.SWINTS.DEEP_SUPERVISION = True
    cfg.MODEL.SWINTS.NO_OBJECT_WEIGHT = 0.1
    cfg.MODEL.SWINTS.MASK_WEIGHT = 2.0

    # Focal Loss.
    cfg.MODEL.SWINTS.ALPHA = 0.25
    cfg.MODEL.SWINTS.GAMMA = 2.0
    cfg.MODEL.SWINTS.PRIOR_PROB = 0.01

    # Optimizer.
    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 1.0

    # Matcher
    cfg.MODEL.SWINTS.IOU_THRESHOLDS = [0.5]
    cfg.MODEL.SWINTS.IOU_LABELS = [0, 1]

    # Encoder
    cfg.MODEL.SWINTS.PATH_COMPONENTS = "./projects/SWINTS/LME/coco_2017_train_class_agnosticTrue_whitenTrue_sigmoidTrue_60_siz28.npz"
    
    # SWINT backbone
    cfg.MODEL.SWINT = CN()
    cfg.MODEL.SWINT.EMBED_DIM = 96
    cfg.MODEL.SWINT.OUT_FEATURES = ["stage2", "stage3", "stage4", "stage5"]
    cfg.MODEL.SWINT.DEPTHS = [2, 2, 6, 2]
    cfg.MODEL.SWINT.NUM_HEADS = [3, 6, 12, 24]
    cfg.MODEL.SWINT.WINDOW_SIZE = 7
    cfg.MODEL.SWINT.MLP_RATIO = 4
    cfg.MODEL.SWINT.DROP_PATH_RATE = 0.2
    cfg.MODEL.SWINT.APE = False
    
    cfg.MODEL.BACKBONE.FREEZE_AT = -1
    cfg.MODEL.BACKBONE.FREEZE_BN = False

    # addation
    cfg.MODEL.FPN.TOP_LEVELS = 2
    cfg.MODEL.FPN.FREEZE = False

    # Test config
    cfg.TEST.USE_NMS_IN_TSET = True
    cfg.TEST.SAMPLE = -1
    cfg.TEST.INFERENCE_TH_TEST = 0.4
    cfg.TEST.RUN_ALL_HEADS = False
    cfg.TEST.DET_CONF_THRESH = 0.4
    cfg.TEST.LANG_CONF_THRESH = 0.4
    cfg.TEST.SEQ_CONF_THRESH = 0.4