_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: "ckpt/swin_imagenet_pretrain.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
DATASETS:
  # TRAIN: ("totaltext_train",)
  TRAIN: ("debug",)
  TEST:  ("debug",)
SOLVER:
  STEPS: (360000,420000)
  MAX_ITER: 450000
  CHECKPOINT_PERIOD: 5000
INPUT:
  FORMAT: "RGB"
